- name: Set up non-world accessible default umask
  block:
    - lineinfile:
        path: /etc/login.defs
        regexp: '^UMASK'
        state: present
        line: UMASK 027
    # Allow root & ubuntu to be world-readable, for software installation
    - lineinfile:
        path: "{{ filename }}"
        state: present
        line: umask 0022
      loop: [ /root/.bashrc, /home/ubuntu/.bashrc ]
      loop_control:
        loop_var: filename

- name: Add user with random password
  block:
  - shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9@#$%*_\-' | fold -w 12 | head -n1
    register: randompass
  - command: "mkpasswd --method=sha-512 {{ randompass.stdout }}"
    register: cryptopass
  - group:
      name: "{{ item.group }}"
      state: present
  - user:
      name: "{{ item.user }}"
      group: "{{ item.group }}"
      groups: [jupyterhub, users]
      password: "{{ cryptopass.stdout }}"
      shell: /bin/bash
  - file:
      path: "/mnt/data/users/{{ item.user }}"
      state: directory
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
      mode: 0750
  - debug:
      msg: "{{ item.user }}  {{ item.group }}  {{ randompass.stdout }}"

- name: Update sshd config to allow ssh for accounts in the users group
  block:
  - blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        Match Group users
          PasswordAuthentication yes
        Match All
  - systemd:
      name: sshd
      enabled: yes
      state: restarted
