- name: Add user with random password
  block:
  - shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9@#$%*_\-' | fold -w 12 | head -n1
    register: randompass
  - command: "mkpasswd --method=sha-512 {{ randompass.stdout }}"
    register: cryptopass
  - group:
      name: "{{ item.group }}"
      state: present
  - user:
      name: "{{ item.user }}"
      group: "{{ item.group }}"
      groups: [jupyterhub, users]
      password: "{{ cryptopass.stdout }}"
      shell: /bin/bash
  - file:
      path: "/mnt/data/users/{{ item.user }}"
      state: directory
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
      mode: 0750
  - file:
      path: "/home/{{ item.user }}"
      mode: 0750
  - debug:
      msg: "{{ item.user }}  {{ item.group }}  {{ randompass.stdout }}"



# Add a group and user later on, with fixed group id and user id:
# groupadd -g 1005 <groupname>
# pw=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9@#$%*_\-' | fold -w 12 | head -n1)
# cryptopass=$(mkpasswd --method=sha-512 $pw)
# useradd -u 1004 -g <groupname> -G jupyterhub,users -m -p $cryptopass -s /bin/bash <username>
