- name: Set up Jupyter account and configuration
  block:
    - group:
        name: jupyterhub
        state: present
    - user:
        name: jupyterhub
        group: jupyterhub
        # Need shadow for PAM authentication
        groups: shadow
        create_home: no
        password: !
        state: present

    - file:
        path: "{{ item }}"
        state: directory
        owner: jupyterhub
        group: jupyterhub
      loop: [/srv/jupyterhub, /etc/jupyterhub]
    - command: /mnt/opt/conda/bin/jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py && chown jupyterhub:jupyterhub /etc/jupyterhub/jupyterhub_config.py
      args:
        creates: /etc/jupyterhub/jupyterhub_config.py
    - lineinfile:
        path: /etc/jupyterhub/jupyterhub_config.py
        state: present
        line: "{{ item }}"
      loop:
        - "c.JupyterHub.bind_url = 'http://127.0.0.1:8000'"
        - "c.Spawner.default_url = '/lab'"
        - "c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'"
        - "c.Spawner.cmd = ['jupyter-labhub']"
        - "#c.Application.log_level = 'DEBUG'"
        - "#c.Spawner.debug = True"
        - "#c.SudoSpawner.debug = True"
        - "# The following settings are used when running JupyterHub by itself, without a proxy"
        - "#c.JupyterHub.bind_url = 'http://server.eucp-nlesc.surf-hosted.nl:8081'"
        - "#c.JupyterHub.ssl_key = '/etc/letsencrypt/live/server.eucp-nlesc.surf-hosted.nl/privkey.pem'"
        - "#c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/server.eucp-nlesc.surf-hosted.nl/fullchain.pem'"

    - copy:
        dest: /mnt/opt/conda/bin/sudospawner-singleuser
        mode: 0755
        content: |
          #!/bin/bash -l
          # Delegate the notebook server launch to the jupyter-labhub script.
          exec "jupyter-labhub" $@
