---
- hosts: all
  vars_files:
    - mount_vars.yml
    - user_vars.yml
  remote_user: ubuntu
  become: true

  tasks:
  - name: Update apt and install packages
    shell: umask 0022 && umask
    register: umask
  - debug:
      msg: "{{ umask .stdout }}"
